metrics:
  port: 9090 # port for prometheus metrics, served on /metrics and /

proxy:
  port: 3000 # port for RPC gateway
  upstreamTimeout: "1s" # when is a request considered timed out

healthChecks:
  interval: "5s" # how often to do healthchecks
  timeout: "1s" # when should the timeout occur and considered unhealthy
  failureThreshold: 2 # how many failed checks until marked as unhealthy
  successThreshold: 1 # how many successes to be marked as healthy again

targets:
  - name: "QuickNode"
    connection:
      http: # ws is supported by default, it will be a sticky connection.
        url: "https://rpc.ankr.com/eth"
        # compression: true # Specify if the target supports request compression
      # optional ws url for Solana configuration
      ws:
        url: "wss://solana.ws.node"

exceptions:
#   String to match in the response body
  - match: "failed to get Arbitrum Node from backend"

  - match: "block range is too wide"

  - match: "block height exceeded"
#   Optional message to send as error message, otherwise match string will send as error message
    message: "Solana: block height exceeded"

  - match: "Blockhash not found"
    message: "Solana: Blockhash not found"

  - match: "Block not available for slot"
    message: "Solana: Block not available for slot"

  - match: "socket hang up"

  - match: "cannot query unfinalized data"

  - match: "missing response for request"

  - match: "after last accepted block"
    message: "requested to block after last accepted block"

solana: false # if gateway is for solana